[package]
name = "obelisk"
version = "0.1.0"
authors = ["Felipe Sere <felipesere@gmai.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[dependencies]
cxx = "0.5"

[build-dependencies]
cxx-build = "0.5"
